Restore password
pgananc/facturacion-electronica pull request #21
Opened 2022-11-25 00:53 UTC by pgananc

2022-11-27 18:26 UTC, jeddiewars requested changes

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/pom.xml
> +			<artifactId>spring-boot-starter-thymeleaf</artifactId>
remover dependencia

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/controller/TokenController.java
> +  public ResponseEntity<Boolean> restablecerClave(@PathVariable("token") String token) {
resetPassword cambiar el nombre del metodo a ingles

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/controller/TokenController.java
> +      if (token != null && !token.isEmpty()) {
no se debe validar a nivel de params? si no manda desde la URL es un bad request para evitar este IF

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/entity/ResetToken.java
> +    public boolean isExpirate() {
isExpired

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/service/IRestTokenService.java
> +    boolean validateTokenActive(String token);
validateActiveToken

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/service/IUserService.java
> +    boolean restorePassword(String token, String password);
resetPassword suena mejor no?

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/service/impl/RestTokenServiceImpl.java
> +        if(Objects.isNull(resetToken)){
use el operador ternario: return Objects.isNull(resetToken)? false: resetToken.isExpirate();

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/service/impl/UserServiceImpl.java
> +@FieldDefaults(level = PRIVATE)
si puede use en todas las clases esta ANOTACION xfa

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/service/impl/UserServiceImpl.java
> +                MailDto mailDto = new MailDto();
No puede usar un @Builder?

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/service/impl/UserServiceImpl.java
> +                ResetToken token = new ResetToken();
use @Builder en la entidad

2022-11-27 18:26 UTC, jeddiewars commented on ebill-utils/src/main/java/com/wallparisoft/ebill/utils/dto/MailDto.java
> +@Data
adicional @Builder, @FieldDefault

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/_service/user/user.service.ts
> +  restore(token: string, clave: string) {
resetPassword tal vez

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/app-routing.module.ts
> +    component: PasswordRestoreComponent,
ResetPasswordComponent... cambie el nombre el orden esta mal xfa

2022-11-27 18:26 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/entity/ResetToken.java
> +public class ResetToken {
tal vez la clase podría ser TokenAdmin

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/password-restore.component.html
> +    Las instrucciones de recuperación de contraseña se enviaran al correo
restablecimiento para continuar con la linea de "restablecer contraseña"

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/password-restore.component.ts
> +export class PasswordRestoreComponent implements OnInit {
ResetPasswordComponent cambiar el nombre o el orden si va a mantener el Restore

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/password-restore.component.ts
> +  get f() {
que hace este metodo?

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +<mat-toolbar *ngIf="tokenValido">
validToken

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +  *ngIf="tokenValido"
validToken

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +  <mat-toolbar *ngIf="mensaje">{{ mensaje }}</mat-toolbar>
message

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  mensaje: string;
message

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  rpta: number;
response

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  tokenValido: boolean;
validToken

2022-11-27 18:26 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +        this.mensaje = 'Se cambio la contraseña';
agregue al final "exitosamente" podría ser no?

2022-11-28 02:33 UTC, pgananc commented on ebill-authentication/pom.xml
> +			<artifactId>spring-boot-starter-thymeleaf</artifactId>
ok

2022-11-28 02:35 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/controller/TokenController.java
> +  public ResponseEntity<Boolean> restablecerClave(@PathVariable("token") String token) {
ok

2022-11-28 03:15 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/controller/TokenController.java
> +      if (token != null && !token.isEmpty()) {
OK

2022-11-28 03:17 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/entity/ResetToken.java
> +    public boolean isExpirate() {
ok

2022-11-28 03:18 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/service/IRestTokenService.java
> +    boolean validateTokenActive(String token);
ok

2022-11-28 03:20 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +  <mat-toolbar *ngIf="mensaje">{{ mensaje }}</mat-toolbar>
ok

2022-11-28 03:21 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  mensaje: string;
ok

2022-11-28 03:22 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  rpta: number;
ok

2022-11-28 03:22 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  tokenValido: boolean;
ok

2022-11-28 03:23 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +        this.mensaje = 'Se cambio la contraseña';
De acuerdo

2022-11-28 12:43 UTC, jeddiewars requested changes

2022-11-28 12:43 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/service/impl/RestTokenServiceImpl.java
> +        if(Objects.isNull(resetToken)){
???

2022-11-28 12:43 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/entity/ResetToken.java
> +public class ResetToken {
confirme que opina ?

2022-11-28 12:45 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/controller/TokenController.java
> +  public ResponseEntity<Boolean> restablecerClave(@PathVariable("token") String token) {
no hay cambio?

2022-11-28 12:46 UTC, jeddiewars commented on ebill-authentication/src/main/java/com/wallparisoft/controller/TokenController.java
> +      if (token != null && !token.isEmpty()) {
no hay cambio?

2022-11-28 12:50 UTC, jeddiewars requested changes

2022-11-28 12:50 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +  *ngIf="tokenValido"
?

2022-11-28 12:50 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +<mat-toolbar *ngIf="tokenValido">
?

2022-11-28 12:50 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +  <mat-toolbar *ngIf="mensaje">{{ mensaje }}</mat-toolbar>
no hay cambio?

2022-11-28 12:50 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/password-restore.component.ts
> +export class PasswordRestoreComponent implements OnInit {
?

2022-11-28 12:50 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/password-restore.component.html
> +    Las instrucciones de recuperación de contraseña se enviaran al correo
?

2022-11-28 12:50 UTC, jeddiewars commented on ebilling-web-app/src/app/app-routing.module.ts
> +    component: PasswordRestoreComponent,
?

2022-11-28 12:50 UTC, jeddiewars commented on ebill-utils/src/main/java/com/wallparisoft/ebill/utils/dto/MailDto.java
> +@Data
??

2022-11-28 13:14 UTC, jeddiewars requested changes

2022-11-28 13:14 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  rpta: number;
?

2022-11-28 13:14 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  mensaje: string;
?

2022-11-28 13:14 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  tokenValido: boolean;
?

2022-11-28 13:14 UTC, jeddiewars commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +        this.mensaje = 'Se cambio la contraseña';
?

2022-11-28 13:18 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/controller/TokenController.java
> +  public ResponseEntity<Boolean> restablecerClave(@PathVariable("token") String token) {
actualizado

2022-11-28 13:18 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/controller/TokenController.java
> +      if (token != null && !token.isEmpty()) {
Actualizado

2022-11-28 13:18 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/entity/ResetToken.java
> +    public boolean isExpirate() {
Actualizado

2022-11-28 13:19 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +  <mat-toolbar *ngIf="mensaje">{{ mensaje }}</mat-toolbar>
Actualizado

2022-11-28 13:19 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  mensaje: string;
Actualizado

2022-11-28 13:19 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  rpta: number;
Actualizado

2022-11-28 13:19 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +  tokenValido: boolean;
Actualizado

2022-11-28 13:19 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.ts
> +        this.mensaje = 'Se cambio la contraseña';
Actualizado

2022-11-28 13:35 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/service/IRestTokenService.java
> +    boolean validateTokenActive(String token);
Actualizado

2022-11-28 13:37 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/service/IUserService.java
> +    boolean restorePassword(String token, String password);
Actualizado

2022-11-28 13:39 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/service/impl/RestTokenServiceImpl.java
> +        if(Objects.isNull(resetToken)){
Actualizado

2022-11-28 13:52 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/service/impl/UserServiceImpl.java
> +                MailDto mailDto = new MailDto();
Actualizado

2022-11-28 13:53 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/service/impl/UserServiceImpl.java
> +                ResetToken token = new ResetToken();
Actualizado

2022-11-28 13:55 UTC, pgananc commented on ebill-utils/src/main/java/com/wallparisoft/ebill/utils/dto/MailDto.java
> +@Data
Actualizado

2022-11-28 14:14 UTC, pgananc commented on ebilling-web-app/src/app/_service/user/user.service.ts
> +  restore(token: string, clave: string) {
Actualizado

2022-11-28 14:25 UTC, pgananc commented on ebill-authentication/src/main/java/com/wallparisoft/entity/ResetToken.java
> +public class ResetToken {
Actualizado

2022-11-28 14:28 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/password-restore.component.ts
> +export class PasswordRestoreComponent implements OnInit {
Actualizado a ResetPasswordComponent

2022-11-28 14:29 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/password-restore.component.ts
> +  get f() {
Devuelve los valores del formulario para validaciones esta siendo utilizado en el html.

2022-11-28 14:30 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +<mat-toolbar *ngIf="tokenValido">
Actualizado

2022-11-28 14:30 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/token/token.component.html
> +  *ngIf="tokenValido"
Actualizado

2022-11-28 14:40 UTC, pgananc commented on ebilling-web-app/src/app/pages/login/password-restore/password-restore.component.html
> +    Las instrucciones de recuperación de contraseña se enviaran al correo
Actualizado a: "Las instrucciones de recuperación de contraseña se enviaran al correo
    electrónico especificado en el registro."

2022-11-28 22:39 UTC, jeddiewars approved these changes

2022-11-28 22:39 UTC, merged